version: 0.2

phases:
    install:
      runtime-versions:
        nodejs: 14
    build:
      commands:
        - (cd ./src && npm install)
        - aws cloudformation package --template ./template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
    files:
        - template-export.yml
