AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Codebuild AWS Lambda deployment

Parameters:
  AppName:
    Type: String
    Description: "Specifies the name of the app and the stage where its called on apigw (ex: https://apigw_addess/appname/)"
  AppVersion:
    Type: String
    Description: "Specifies the version of the app (is displayed in the response)"
  DNSZoneId:
    Type: String
    Description: "DNS Zone Id"
  DNSZoneName:
    Type: String
    Description: "DNS Zone HostName"

Resources:
  DNSZoneCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${AppName}.${DNSZoneName}'
      DomainValidationOptions:
        - DomainName: !Sub '${AppName}.${DNSZoneName}'
          HostedZoneId: !Ref DNSZoneId
      ValidationMethod: DNS

  ApiGW:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: !Join [ '_', !Split [ '.', !Ref AppVersion ] ]
      Domain:
        CertificateArn: !Ref DNSZoneCertificate
        DomainName: !Sub '${AppName}.${DNSZoneName}'
        Route53:
          HostedZoneId: !Ref DNSZoneId
        SecurityPolicy: TLS_1_2

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: src/
      Description: Codebuild aws lambda example
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DEBUG: "beameio:*"
          APP_VERSION: !Ref AppVersion
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGW
            Path: /
            Method: ANY
        ProxyAny:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGW
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - !Sub https://${AppName}.${DNSZoneName}/
        - !Join [ '_', !Split [ '.', !Ref AppVersion ] ]
        - '/'