AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Codebuild AWS Lambda deployment

Parameters:
  ApiGWId:
    Type: String
  AppPath:
    Type: String
    Description: "Specifies the path where the app is called (ex: https://apigw_addess/path/)"
  AppVersion:
    Type: String
    Description: "Specifies the version of the app (is displayed in the response)"
    Default: "v1.0"
Resources:
  LambdaFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: src/
      Description: Codebuild aws lambda example
      MemorySize: 123
      Timeout: 30
      Environment:
        Variables:
          DEBUG: "beameio:*"
          APP_VERSION: !Ref AppVersion
      Events:
        ProxyAny:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGWId
            Path: !Sub '/${AppPath}/{proxy+}'
            Method: any